#!/bin/bash
#
# tagent: Custom Agent Service
#
# chkconfig: 345 99 10
# description: Custom agent service that runs /opt/ed/agent with a configuration file.
# processname: tagent

# Source function library.
. /etc/rc.d/init.d/functions

start() {
    echo "Starting tagent"
    /opt/ed/agent/agent -c /opt/ed/config.yml &
    daemon /opt/ed/agent/agent
}

stop() {
    echo "Stopping tagent"
    killproc /opt/ed/agent/agent
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    status)
        status /opt/ed/agent/agent
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
